### PR TITLE
Fix typos in source comments and user-facing output

### PR DESCRIPTION
**Pull request by luzpaz**
Found using `codespell -q 3 -L ba,currenty`

### CODE REVIEW

**Comment by luzpaz** [comment]
Follow-up Questions: 
1. is the doxygen .html content generated? Or should I submit typo fixes for those as well ?
2. there are some API typos like `reseting` and `Consol`, would you like me to submit fixes for those ?

**Comment by JiriValasek** [comment]
Hi luzpaz, 

thanks for contributions. Unfortunately, this project is a part of my diploma thesis an as such it would be inappropriate from me to accept external help at this time. However, I am going to check for those typos and I'll be gladly accepting all help after the thesis defense i.e. from February 2020 onward. 

Thanks for understanding

**Comment by luzpaz** [comment]
No worries, I need no attribution. If you want to sanitize them of my personal info, that's fine.

**Comment by luzpaz** [comment]
https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by JiriValasek** [comment]
I guess I'll check it with the codespell myself, I've never used it and it seems like a useful thing to learn. Anyway thanks for notifying me about this.

**Comment by luzpaz** [comment]
:+1:  
I wish you continued success on this endeavor.

**Pull request closed without merging**
